name: Deploy to Staging

on:
  push:
    branches: [ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything on the staging server
    steps:
      - name: Deploy
        env:
          SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem root@157.245.109.220 << 'EOF'
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            source ~/.profile || true
            
            cd BMS-deployment
            git pull
            pnpm install
            pnpm run build
            pm2 restart http-server
            pm2 restart ws-server
            pm2 restart fe-server
          EOF

